force-app/main/default/objects/Federal_Withholding__mdt/Federal_Withholding__mdt.object-meta.xml
<CustomObject>
    <description>Federal Tax Brackets to use in take home calculations</description>
    <label>Federal Withholding</label>
    <pluralLabel>Federal Withholdings</pluralLabel>
</CustomObject>

force-app/main/default/objects/Federal_Withholding__mdt/fields/Bracket_End__c.field-meta.xml
<CustomField>
    <fullName>Bracket_End__c</fullName>
    <description>The dollar amount that the bracket ends at</description>
    <label>Bracket End</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Federal_Withholding__mdt/fields/Bracket_Start__c.field-meta.xml
<CustomField>
    <fullName>Bracket_Start__c</fullName>
    <description>The dollar amount that a given tax bracket starts at</description>
    <label>Bracket Start</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Federal_Withholding__mdt/fields/Federal_Tax_Filing_Status__c.field-meta.xml
<CustomField>
    <fullName>Federal_Tax_Filing_Status__c</fullName>
    <description>Federal Tax Filing Status, since this impacts the Federal Withholding</description>
    <label>Federal Tax Filing Status</label>
    <referenceTo>Federal_Tax_Filing_Status__mdt</referenceTo>
    <relationshipLabel>Federal Withholdings</relationshipLabel>
    <relationshipName>Federal_Withholdings</relationshipName>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/Federal_Withholding__mdt/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <description>Order of the tax bracket within its Filing Status from lowest income to highest income</description>
    <label>Order</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Federal_Withholding__mdt/fields/Tax_Rate__c.field-meta.xml
<CustomField>
    <fullName>Tax_Rate__c</fullName>
    <description>The % tax rate on earnings over the start of the bracket</description>
    <label>Tax Rate</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Federal_Withholding__mdt/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>The type of federal withholding</description>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Federal Income Tax</fullName>
                <default>true</default>
                <label>Federal Income Tax</label>
            </value>
            <value>
                <fullName>Medicare</fullName>
            </value>
            <value>
                <fullName>Social Security</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/FederalWithholdingSelector.cls
public with sharing class FederalWithholdingSelector {

    public static List<Federal_Withholding__mdt> getFederalWithholdingsForStatus(Id federalTaxStatusCmdtId) {

        if (federalTaxStatusCmdtId == null) {
            Utility.throwIllegalArgumentException('The federalTaxStatus argument was null.');
        }

        List<Federal_Withholding__mdt> withholdings = [
            SELECT Id, Bracket_Start__c, Bracket_End__c, DeveloperName, Order__c, Tax_Rate__c, Type__c, Federal_Tax_Filing_Status__c
            FROM Federal_Withholding__mdt
            WHERE Type__c = 'Federal Income Tax' 
            AND Federal_Tax_Filing_Status__c = :federalTaxStatusCmdtId
            ORDER BY Order__c
        ];
        if (withholdings.isEmpty()) {
            Utility.throwQueryException('The Federal Tax Filing Status has no withholding data in the CMDT');
        }
        return withholdings;
    }
}