force-app/main/default/objects/Federal_Tax_Filing_Status__mdt/Federal_Tax_Filing_Status__mdt.object-meta.xml
<CustomObject>
    <description>Stores the Standard Deduction for different tax filing statuses so they can used in code</description>
    <label>Federal Tax Filing Status</label>
    <pluralLabel>Federal Tax Filing Statuses</pluralLabel>
</CustomObject>

force-app/main/default/objects/Federal_Withholding__mdt/Federal_Withholding__mdt.object-meta.xml
<CustomObject>
    <description>Federal Tax Brackets to use in take home calculations</description>
    <label>Federal Withholding</label>
    <pluralLabel>Federal Withholdings</pluralLabel>
</CustomObject>

force-app/main/default/objects/Federal_Withholding__mdt/fields/Federal_Tax_Filing_Status__c.field-meta.xml
<CustomField>
    <fullName>Federal_Tax_Filing_Status__c</fullName>
    <description>Federal Tax Filing Status, since this impacts the Federal Withholding</description>
    <label>Federal Tax Filing Status</label>
    <referenceTo>Federal_Tax_Filing_Status__mdt</referenceTo>
    <relationshipLabel>Federal Withholdings</relationshipLabel>
    <relationshipName>Federal_Withholdings</relationshipName>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/Federal_Withholding__mdt/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <description>Order of the tax bracket within its Filing Status from lowest income to highest income</description>
    <label>Order</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Federal_Withholding__mdt/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>The type of federal withholding</description>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Federal Income Tax</fullName>
                <default>true</default>
                <label>Federal Income Tax</label>
            </value>
            <value>
                <fullName>Medicare</fullName>
            </value>
            <value>
                <fullName>Social Security</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/FederalWithholdingSelectorTest.cls
@isTest
public with sharing class FederalWithholdingSelectorTest {

    @isTest
    static void getFederalWithholdingsForStatus_expectedResults() {

        Id taxStatusId = Federal_Tax_Filing_Status__mdt.getInstance('Married_Filing_Jointly').Id;

        Test.startTest();
        List<Federal_Withholding__mdt> withholdings = FederalWithholdingSelector.getFederalWithholdingsForStatus(taxStatusId);
        Test.stopTest();

        Decimal lastOrderByValue = null;
        for (Federal_Withholding__mdt withholding : withholdings) {
            Assert.isTrue(withholding.Federal_Tax_Filing_Status__c == taxStatusId, 
                'The Federal Tax Filing Status should be ' + taxStatusId + '. It is ' + withholding.Federal_Tax_Filing_Status__c);
            Assert.isTrue(withholding.Type__c == 'Federal Income Tax', 
                'The withholding Type should be Federal Income Tax. It is ' + withholding.Type__c);
            Assert.isTrue(withholding.Order__c > lastOrderByValue || (withholding.Order__c != null & lastOrderByValue == null), 
                'The Order value should be greater than ' + lastOrderByValue + '. It is ' + withholding.Order__c);
            lastOrderByValue = withholding.Order__c;
        }
    }

    @isTest
    static void getFederalWithholdingsForStatus_illegalArgument(){

        Id taxStatusId = null;
        Boolean exceptionThrown = false;

        Test.startTest();
        try {
            List<Federal_Withholding__mdt> withholdings = FederalWithholdingSelector.getFederalWithholdingsForStatus(taxStatusId);
        } catch (IllegalArgumentException e) {
            exceptionThrown = true;
        }
        Test.stopTest();

        Assert.isTrue(exceptionThrown, 'An Illegal Argument Exception should have been thrown,');
    }
}