force-app/main/default/objects/Job_Application__c/Job_Application__c.object-meta.xml
<CustomObject>
    <description>Tracks Job Applications throughout the whole lifecycle of the application.</description>
    <label>Job Application</label>
    <nameField>
        <displayFormat>JA-{00000}</displayFormat>
        <label>Job Application Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Job_Application__c/fields/Application_Status__c.field-meta.xml
<CustomField>
    <fullName>Application_Status__c</fullName>
    <description>The Status of the Job Application</description>
    <inlineHelpText>The Status of the Job Application</inlineHelpText>
    <label>Application Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Saved</fullName>
                <default>true</default>
                <label>Saved</label>
            </value>
            <value>
                <fullName>Not Interested</fullName>
            </value>
            <value>
                <fullName>Applying</fullName>
            </value>
            <value>
                <fullName>Applied</fullName>
            </value>
            <value>
                <fullName>Interviewing</fullName>
            </value>
            <value>
                <fullName>Negotiating</fullName>
            </value>
            <value>
                <fullName>Offer Declined</fullName>
            </value>
            <value>
                <fullName>Offer Accepted</fullName>
            </value>
            <value>
                <fullName>No Offer</fullName>
            </value>
            <value>
                <fullName>Auto Close - Stale</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CloseStaleJobsBatch.cls
public with sharing class CloseStaleJobsBatch implements Database.Batchable<sObject>, Database.Stateful{

    private Set<String> jobAppOwnerEmails = new Set<String>();
    private Integer recordsProcessed = 0;
    @TestVisible private static final String STATUS_TO_SET = 'Auto Close - Stale';
    @TestVisible private static final Integer DAYS_AGO_SINCE_FOLLOW_UP_TO_BE_STALE = 30;
    
    public Database.QueryLocator start(Database.BatchableContext BC){
        Date staleDate = Date.today().addDays(-DAYS_AGO_SINCE_FOLLOW_UP_TO_BE_STALE);
        return Database.getQueryLocator(JobApplicationSelector.getStaleJobApplications(staleDate));
    }
    
    public void execute(Database.BatchableContext BC, List<Job_Application__c> scope){
        
        for (Job_Application__c jobApp : scope) {
            jobApp.Application_Status__c = STATUS_TO_SET;
            if (jobApp.Owner.isActive){
                jobAppOwnerEmails.add(jobApp.Owner.Email);
            }
        }
        try {
            update scope;
            recordsProcessed += scope.size();
        } catch (DmlException e) {
            Utility.throwDmlException(e);
        }
    }
    
    public void finish(Database.BatchableContext BC){

        if(recordsProcessed >= 1 && !jobAppOwnerEmails.isEmpty()) {
            try {
                Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
                mail.setToAddresses(new List<String>(jobAppOwnerEmails));
                mail.setSubject('Stale Job Applications Closed');
                mail.setPlainTextBody('Stale Job Applications have been updated to the status: ' + STATUS_TO_SET);
                Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mail });
            } catch (Exception e) {
                Utility.throwHandledException('There was a problem sending an email');
            }
        }
    }
}