force-app/main/default/objects/Job_Application__c/Job_Application__c.object-meta.xml
<CustomObject>
    <description>Tracks Job Applications throughout the whole lifecycle of the application.</description>
    <label>Job Application</label>
    <nameField>
        <displayFormat>JA-{00000}</displayFormat>
        <label>Job Application Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Status_Task_Manager__mdt/Status_Task_Manager__mdt.object-meta.xml
<CustomObject>
    <description>Represents the order of statuses in a business process and is used to determine Tasks to create at different steps as well as validating steps in the process aren&apos;t skipped. If two Statuses are different paths at the same point in the process, they should have the same value in the Order field. For example, for Job Application, Declined, Accepted and No Offer all have the same value. Task creation is optional at each status.</description>
    <label>Status Task Manager</label>
    <pluralLabel>Status Task Manager</pluralLabel>
</CustomObject>

force-app/main/default/objects/Status_Task_Manager__mdt/fields/Default_Days_For_Task_Due_Date__c.field-meta.xml
<CustomField>
    <fullName>Default_Days_For_Task_Due_Date__c</fullName>
    <description>The default number of days to add to the Task Due Date. The code can ignore this and use another value if needed.</description>
    <label>Default Days For Task Due Date</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Status_Task_Manager__mdt/fields/Default_Task_Priority__c.field-meta.xml
<CustomField>
    <fullName>Default_Task_Priority__c</fullName>
    <description>The default Task Priority for a Task that is generated. If a different Task is the required, the code doesn&apos;t need to use it.</description>
    <label>Default Task Priority</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Status_Task_Manager__mdt/fields/Default_Task_Status__c.field-meta.xml
<CustomField>
    <fullName>Default_Task_Status__c</fullName>
    <description>The default Task Status to set. The code doesn&apos;t need to use this and can apply a different status</description>
    <label>Default Task Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/StatusTMJobAppApplied.cls
public with sharing class StatusTMJobAppApplied implements StatusTaskManager {
    
    public List<Task> generateStatusTasks (List<Job_Application__c> jobAppsNeedingTasks, Status_Task_Manager__mdt statusConfig) {
        
        if (jobAppsNeedingTasks.isEmpty() || statusConfig == null) {
            Utility.throwIllegalArgumentException('Arguments passed to the method are null');
        }
        
        // Set default fields used for all Tasks in this Status
        Task taskWithDefaultFields = new Task();
        taskWithDefaultFields.ActivityDate = Date.today() + Integer.valueOf(statusConfig.Default_Days_For_Task_Due_Date__c);
        taskWithDefaultFields.Priority  = statusConfig.Default_Task_Priority__c;
        taskWithDefaultFields.Status = statusConfig.Default_Task_Status__c;
        List<Task> newTasks = new List<Task>();
        for (Job_Application__c jobApp : jobAppsNeedingTasks) {

            taskWithDefaultFields.WhatId = jobApp.Id;

            Task reachOutTask = taskWithDefaultFields.clone();
            reachOutTask.Subject = 'Reach out to the hiring manager or recruiter';
            newTasks.add(reachOutTask);

            Task weeklyFollowUpTask = taskWithDefaultFields.clone();
            weeklyFollowUpTask.Subject = 'Follow up on your application via email weekly';
            newTasks.add(weeklyFollowUpTask);

            Task similarOppsTask = taskWithDefaultFields.clone();
            similarOppsTask.Subject = 'Continue identifying and saving similar job opportunities';
            newTasks.add(similarOppsTask);

            Task weeklyNetworkingCallsTask = taskWithDefaultFields.clone();
            weeklyNetworkingCallsTask.Subject = 'Set up weekly networking calls to explore similar companies/roles';
            newTasks.add(weeklyNetworkingCallsTask);
        }
    return newTasks;
    }
}