force-app/main/default/objects/Job_Application__c/Job_Application__c.object-meta.xml
<CustomObject>
    <description>Tracks Job Applications throughout the whole lifecycle of the application.</description>
    <label>Job Application</label>
    <nameField>
        <displayFormat>JA-{00000}</displayFormat>
        <label>Job Application Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Job_Application__c/fields/Job_Title__c.field-meta.xml
<CustomField>
    <fullName>Job_Title__c</fullName>
    <description>Title of the Job</description>
    <inlineHelpText>Title of the Job the application is for</inlineHelpText>
    <label>Job Title</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Job_Application__c/fields/Salary__c.field-meta.xml
<CustomField>
    <fullName>Salary__c</fullName>
    <description>Salaries from job postings are received as a String and can sometimes be ranges with non numeric characters (e.g. $100 - $150k). The original string received from the posting will be stored in Salary_From_Job_Board__c. Code will then take that value and convert it into a single salary that can be stored in this field.</description>
    <inlineHelpText>The salary from the job posting. If the job posting listed a range, this will be the midpoint in the range.</inlineHelpText>
    <label>Salary</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Job_Application__c/fields/Salary_From_Job_Board__c.field-meta.xml
<CustomField>
    <fullName>Salary_From_Job_Board__c</fullName>
    <description>The salary pulled in from a third-party job board. Since Jooble salaries are stored as a String, this field will hold whatever value is in their data.</description>
    <inlineHelpText>The salary listed on the website that lists the job.</inlineHelpText>
    <label>Salary From Job Board</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/SObjectSalaryConvert_DollarPerHRangeTest.cls
@isTest
public with sharing class SObjectSalaryConvert_DollarPerHRangeTest {

    static final Set<String> VALUES_MEETING_PATTERN = new Set<String>{
        '$5 per hour - $500 per hour', '$5 per hour - $50 per hour', '$50 per hour - $100 per hour', 
        '$5 - $500 per hour', '$5 - $50 per hour','$50 - $100 per hour', 
        '$50.50 per hour - $100.50 per hour', '$50.50 - $100.50 per hour'
    };
    static final Set<String> VALUES_NOT_MEETING_PATTERN = new Set<String>{
        '100k', '50k', '5k', '$5', '$10', '$100', '50k - 100k', '$100k', '$50k', '$5k','5k - 100k', 
        '5k - 10k', '$50 - $100', '$50k - $100k', '$5k - $100k', '$5k - $10k', '50 per hour', '$5 per hour - $500', 
        '$5 per hour - $50', '$50 per hour - $100', '$5 per hour', '$50 per hour', '$100 per hour', '$5.50 per hour',
        '$50.5 per hour', '$100.50 per hour'
    };

    @isTest
    static void checkSalaryPatternAndConvert_patternMatchesAndNotMatches(){

        Set<String> allValues = new Set<String>();
        allValues.addAll(VALUES_MEETING_PATTERN);
        allValues.addAll(VALUES_NOT_MEETING_PATTERN);

        List<Job_Application__c> jobAppsToCheck = new List<Job_Application__c>();
        for (String value : allValues) {
            Job_Application__c jobAppToCheck = new Job_Application__c();
            jobAppToCheck.Salary_From_Job_Board__c = value;
            jobAppsToCheck.add(jobAppToCheck);
        }

        Test.startTest();
        SObjectSalaryConvert_DollarPerHourRange salaryCheck = new SObjectSalaryConvert_DollarPerHourRange();
        salaryCheck.checkSalaryPatternAndConvert(jobAppsToCheck, 'Salary_From_Job_Board__c', 'Salary__c');
        List<Job_Application__c> jobsNotMeetingPattern = salaryCheck.getSObjectsNotMatchingPattern();
        Test.stopTest();

        Assert.areEqual(VALUES_NOT_MEETING_PATTERN.size(), jobsNotMeetingPattern.size(), 
            'The amount of jobs not meeting the pattern is not correct');
        for (Job_Application__c job : jobsNotMeetingPattern) {
            Assert.isTrue(VALUES_NOT_MEETING_PATTERN.contains(job.Salary_From_Job_Board__c), 
                'The Salary should be in the Set of values not meeting the pattern');
            Assert.isFalse(VALUES_MEETING_PATTERN.contains(job.Salary_From_Job_Board__c),
                'The Salary should not be in the Set of values meeting the pattern');
            Assert.isNull(job.Salary__c, 
                'The Salary fied should be null since the pattern was not met.');
        }
    }

    @isTest
    static void checkSalaryPatternAndConvert_checkWrongField(){

        Set<String> allValues = new Set<String>();
        allValues.addAll(VALUES_MEETING_PATTERN);
        allValues.addAll(VALUES_NOT_MEETING_PATTERN);

        List<Job_Application__c> jobAppsToCheck = new List<Job_Application__c>();
        for (String value : allValues) {
            Job_Application__c jobAppToCheck = new Job_Application__c();
            jobAppToCheck.Salary_From_Job_Board__c = value;
            jobAppToCheck.Job_Title__c = 'Test Title';
            jobAppsToCheck.add(jobAppToCheck);
        }

        Test.startTest();
        SObjectSalaryConvert_DollarPerHourRange salaryCheck = new SObjectSalaryConvert_DollarPerHourRange();
        salaryCheck.checkSalaryPatternAndConvert(jobAppsToCheck, 'Job_Title__c', 'Salary__c');
        List<Job_Application__c> jobsNotMeetingPattern = salaryCheck.getSObjectsNotMatchingPattern();
        Test.stopTest();

        Assert.areEqual(allValues.size(), jobsNotMeetingPattern.size(), 
            'The amount of jobs not meeting the pattern is not correct');
    }

    @isTest
    static void checkSalaryPatternAndConvert_checkNullValue(){

        Set<String> allValues = new Set<String>();
        allValues.addAll(VALUES_MEETING_PATTERN);
        allValues.addAll(VALUES_NOT_MEETING_PATTERN);

        List<Job_Application__c> jobAppsToCheck = new List<Job_Application__c>();
        for (String value : allValues) {
            Job_Application__c jobAppToCheck = new Job_Application__c();
            jobAppsToCheck.add(jobAppToCheck);
        }

        Test.startTest();
        SObjectSalaryConvert_DollarPerHourRange salaryCheck = new SObjectSalaryConvert_DollarPerHourRange();
        salaryCheck.checkSalaryPatternAndConvert(jobAppsToCheck, 'Salary_From_Job_Board__c', 'Salary__c');
        List<Job_Application__c> jobsNotMeetingPattern = salaryCheck.getSObjectsNotMatchingPattern();
        Test.stopTest();

        Assert.areEqual(allValues.size(), jobsNotMeetingPattern.size(), 
            'The amount of jobs not meeting the pattern is not correct');
    }

    @isTest
    static void checkSalaryPatternAndConvert_emptyJobsToCheck(){

        Set<String> allValues = new Set<String>();
        allValues.addAll(VALUES_MEETING_PATTERN);
        allValues.addAll(VALUES_NOT_MEETING_PATTERN);

        List<Job_Application__c> jobAppsToCheck = new List<Job_Application__c>();
        Boolean exceptionThrown = false;

        Test.startTest();
        try {
            SObjectSalaryConvert_DollarPerHourRange salaryCheck = new SObjectSalaryConvert_DollarPerHourRange();
            salaryCheck.checkSalaryPatternAndConvert(jobAppsToCheck, 'Salary_From_Job_Board__c', 'Salary__c');
            List<Job_Application__c> jobsNotMeetingPattern = salaryCheck.getSObjectsNotMatchingPattern();
        } catch (IllegalArgumentException e) {
            exceptionThrown = true;
        }
        Test.stopTest();

        Assert.isTrue(exceptionThrown, 'An Illegal Argument Exception should have been thrown');
    }

    @isTest
    static void checkSalaryPatternAndConvert_nullFieldToCheck(){

        Set<String> allValues = new Set<String>();
        allValues.addAll(VALUES_MEETING_PATTERN);
        allValues.addAll(VALUES_NOT_MEETING_PATTERN);

        List<Job_Application__c> jobAppsToCheck = new List<Job_Application__c>();
        for (String value : allValues) {
            Job_Application__c jobAppToCheck = new Job_Application__c();
            jobAppToCheck.Salary_From_Job_Board__c = value;
            jobAppsToCheck.add(jobAppToCheck);
        }
        String nullFieldToCheck = null;
        Boolean exceptionThrown = false;

        Test.startTest();
        try {
            SObjectSalaryConvert_DollarPerHourRange salaryCheck = new SObjectSalaryConvert_DollarPerHourRange();
            salaryCheck.checkSalaryPatternAndConvert(jobAppsToCheck, nullFieldToCheck, 'Salary__c');
            List<Job_Application__c> jobsNotMeetingPattern = salaryCheck.getSObjectsNotMatchingPattern();
        } catch (IllegalArgumentException e) {
            exceptionThrown = true;
        }
        Test.stopTest();

        Assert.isTrue(exceptionThrown, 'An Illegal Argument Exception should have been thrown');
    }

    @isTest
    static void checkSalaryPatternAndConvert_nullFieldToSet(){

        Set<String> allValues = new Set<String>();
        allValues.addAll(VALUES_MEETING_PATTERN);
        allValues.addAll(VALUES_NOT_MEETING_PATTERN);

        List<Job_Application__c> jobAppsToCheck = new List<Job_Application__c>();
        for (String value : allValues) {
            Job_Application__c jobAppToCheck = new Job_Application__c();
            jobAppToCheck.Salary_From_Job_Board__c = value;
            jobAppsToCheck.add(jobAppToCheck);
        }
        String nullFieldToSet = null;
        Boolean exceptionThrown = false;

        Test.startTest();
        try {
            SObjectSalaryConvert_DollarPerHourRange salaryCheck = new SObjectSalaryConvert_DollarPerHourRange();
            salaryCheck.checkSalaryPatternAndConvert(jobAppsToCheck, 'Salary_From_Job_Board__c', nullFieldToSet);
            List<Job_Application__c> jobsNotMeetingPattern = salaryCheck.getSObjectsNotMatchingPattern();
        } catch (IllegalArgumentException e) {
            exceptionThrown = true;
        }
        Test.stopTest();

        Assert.isTrue(exceptionThrown, 'An Illegal Argument Exception should have been thrown');
    }
}