force-app/main/default/objects/Job_Application__c/Job_Application__c.object-meta.xml
<CustomObject>
    <description>Tracks Job Applications throughout the whole lifecycle of the application.</description>
    <label>Job Application</label>
    <nameField>
        <displayFormat>JA-{00000}</displayFormat>
        <label>Job Application Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Job_Application_Contact__c/Job_Application_Contact__c.object-meta.xml
<CustomObject>
    <description>Junction Object between Job Application and Contact so that there can be a many to many relationship between the two.</description>
    <label>Job Application Contact</label>
    <nameField>
        <displayFormat>JAC-{0000}</displayFormat>
        <label>Job Application Contact Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Application Contacts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Job_Application_Contact__c/fields/Job_Application__c.field-meta.xml
<CustomField>
    <fullName>Job_Application__c</fullName>
    <description>Primary Master-Detail relationship for the Junction Object.</description>
    <inlineHelpText>Job Application associated with the Job Application Contact</inlineHelpText>
    <label>Job Application</label>
    <referenceTo>Job_Application__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Job_Application_Contacts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Job_Application_Contact__c/fields/Primary_Contact__c.field-meta.xml
<CustomField>
    <fullName>Primary_Contact__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates if the Contact associated with the Job Application is the Primary Contact.</description>
    <inlineHelpText>Indicates if the Contact associated with the Job Application is the Primary Contact.</inlineHelpText>
    <label>Primary Contact</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Job_Application_Contact__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <description>Role of the Contact in the Job Application.</description>
    <inlineHelpText>Role of the associated Contact in the associated Job Application.</inlineHelpText>
    <label>Role</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Hiring Manager</fullName>
            </value>
            <value>
                <fullName>Recruiter</fullName>
            </value>
            <value>
                <fullName>Team Member</fullName>
            </value>
            <value>
                <fullName>Existing Contact</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/JobApplicationContactSelector.cls
public with sharing class JobApplicationContactSelector {

    public static List<Job_Application_Contact__c> getJobApplicationContactsByRole (Set<Id> jobAppIds, String role) {

        if (jobAppIds.isEmpty()) {
            Utility.throwIllegalArgumentException('The jobAppIds arugment doesn not have any Ids');
        }

        List<Job_Application_Contact__c> jobAppContacts = [
            SELECT Id, Role__c, Primary_Contact__c, Job_Application__c
            FROM Job_Application_Contact__c
            WHERE Job_Application__c IN :jobAppIds
            AND Role__c = :role
        ];
        return jobAppContacts;
    }

    public static List<Job_Application_Contact__c> getPrimaryContactsForJobApps (Set<Id> jobAppIds) {

        if (jobAppIds.isEmpty()) {
            Utility.throwIllegalArgumentException('The jobAppIds argument is null');
        }

        List<Job_Application_Contact__c> primaryJobAppContacts = [
            SELECT Id, Primary_Contact__c, Job_Application__c
            FROM Job_Application_Contact__c
            WHERE Job_Application__c IN :jobAppIds
            AND Primary_Contact__c = TRUE
        ];
        return primaryJobAppContacts;
    }

    public static List<Job_Application_Contact__c> getPrimaryContactsForJobAppsExcludingCertainContacts (Set<Id> jobAppIds, Set<Id> jobAppContactIdsToNotGet) {

        if (jobAppIds.isEmpty() || jobAppContactIdsToNotGet.isEmpty()) {
            Utility.throwIllegalArgumentException('Arguments passed to the method were null');
        }

        List<Job_Application_Contact__c> primaryJobAppContacts = [
            SELECT Id, Primary_Contact__c, Job_Application__c
            FROM Job_Application_Contact__c
            WHERE Job_Application__c IN :jobAppIds
            AND Id NOT IN :jobAppContactIdsToNotGet
            AND Primary_Contact__c = TRUE
        ];
        return primaryJobAppContacts;

    }
}