force-app/main/default/objects/Job_Application__c/Job_Application__c.object-meta.xml
<CustomObject>
    <description>Tracks Job Applications throughout the whole lifecycle of the application.</description>
    <label>Job Application</label>
    <nameField>
        <displayFormat>JA-{00000}</displayFormat>
        <label>Job Application Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Job_Application__c/fields/Application_Status__c.field-meta.xml
<CustomField>
    <fullName>Application_Status__c</fullName>
    <description>The Status of the Job Application</description>
    <inlineHelpText>The Status of the Job Application</inlineHelpText>
    <label>Application Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Saved</fullName>
                <default>true</default>
                <label>Saved</label>
            </value>
            <value>
                <fullName>Not Interested</fullName>
            </value>
            <value>
                <fullName>Applying</fullName>
            </value>
            <value>
                <fullName>Applied</fullName>
            </value>
            <value>
                <fullName>Interviewing</fullName>
            </value>
            <value>
                <fullName>Negotiating</fullName>
            </value>
            <value>
                <fullName>Offer Declined</fullName>
            </value>
            <value>
                <fullName>Offer Accepted</fullName>
            </value>
            <value>
                <fullName>No Offer</fullName>
            </value>
            <value>
                <fullName>Auto Close - Stale</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Job_Application__c/fields/Job_Posting_Id__c.field-meta.xml
<CustomField>
    <fullName>Job_Posting_Id__c</fullName>
    <description>The Id of the Job Posting from the external website</description>
    <externalId>true</externalId>
    <inlineHelpText>The Id of the job posting listed on the external website</inlineHelpText>
    <label>Job Posting Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Status_Task_Manager__mdt/Status_Task_Manager__mdt.object-meta.xml
<CustomObject>
    <description>Represents the order of statuses in a business process and is used to determine Tasks to create at different steps as well as validating steps in the process aren&apos;t skipped. If two Statuses are different paths at the same point in the process, they should have the same value in the Order field. For example, for Job Application, Declined, Accepted and No Offer all have the same value. Task creation is optional at each status.</description>
    <label>Status Task Manager</label>
    <pluralLabel>Status Task Manager</pluralLabel>
</CustomObject>

force-app/main/default/objects/Status_Task_Manager__mdt/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>The Status that can be searched for to find the needed Task to create</description>
    <label>Status</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Status_Task_Manager__mdt/fields/Task_Generation_Class__c.field-meta.xml
<CustomField>
    <fullName>Task_Generation_Class__c</fullName>
    <description>The name of the Class that should be used to generate the Tasks for this status. No value is valid if no Tasks are required at that stage</description>
    <label>Task Generation Class</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/JobApplicationSelectorTest.cls
@isTest
public with sharing class JobApplicationSelectorTest {

    @TestSetup
    static void createAccounts(){
        TestDataFactory.generateAccountsById(200);
    }

    @isTest
    static void getJobAppsWithExternalJobId() {

        List<Account> testAccounts = [SELECT Id FROM Account];
        List<Job_Application__c> jobApps = TestDataFactory.generateJobAppsOnAccount(false, testAccounts);
        Set<String> externalJobAppIds = new Set<String>();
        Integer loopCount = 1;
        for (Job_Application__c jobApp : jobApps) {
            if (loopCount <= 100) {
                jobApp.Job_Posting_Id__c = String.valueOf(loopCount);
                externalJobAppIds.add(String.valueOf(loopCount));
                loopCount++;
            } else {
                break;
            }
        }
        insert jobApps;
        Set<Id> jobAppIdsWithExternalIds = new Set<Id>();
        for (Job_Application__c jobApp : jobApps) {
            if (jobApp.Job_Posting_Id__c != null) {
                jobAppIdsWithExternalIds.add(jobApp.Id);
            }
        }
        Test.startTest();
        List<Job_Application__c> queryResults = JobApplicationSelector.getJobAppsWithExternalJobId(externalJobAppIds);
        Test.stopTest();

        Assert.areEqual(externalJobAppIds.size(), queryResults.size(), 'The expected amount of Job Apps was not returned');
        for (Job_Application__c jobApp : queryResults) {
            Assert.isTrue(jobAppIdsWithExternalIds.contains(jobApp.Id));
        }
    }

    @isTest
    static void getJobAppsWithOpenTasks() {

        // Create Account and Job Apps with a status that will generate open Tasks
        List<Account> testAccounts = [SELECT Id FROM Account];
        List<Job_Application__c> jobApps = TestDataFactory.generateJobAppsOnAccount(false, testAccounts);
        Status_Task_Manager__mdt stm = [
            SELECT Id, Status__c
            FROM Status_Task_Manager__mdt
            WHERE Task_Generation_Class__c != null
            LIMIT 1
        ];
        for (Job_Application__c jobApp : jobApps) {
            jobApp.Application_Status__c = stm.Status__c;
        }
        insert jobApps;
        Set<Id> jobAppIds = new Set<Id>();
        for (Job_Application__c jobApp : jobApps) {
            jobAppIds.add(jobApp.Id);
        }
        
        Test.startTest();
        List<Job_Application__c> queryResults = JobApplicationSelector.getJobAppsWithOpenTasks(jobAppIds);
        Test.stopTest();

        for (Job_Application__c jobApp : queryResults) {
            List<Task> childTasks = jobApp.Tasks;
            Assert.isFalse(childTasks.isEmpty(), 'The Job App does not have any Tasks');
            Integer countOfOpenTasks = 0;
            for (Task childTask : childTasks) {
                if (!childTask.isClosed) {
                    countOfOpenTasks++;
                }
            }
            Assert.isTrue(countOfOpenTasks >= 1, 'The Job App does not have child Tasks');
        }
    }
}