force-app/main/default/objects/Job_Application__c/Job_Application__c.object-meta.xml
<CustomObject>
    <description>Tracks Job Applications throughout the whole lifecycle of the application.</description>
    <label>Job Application</label>
    <nameField>
        <displayFormat>JA-{00000}</displayFormat>
        <label>Job Application Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Job_Application__c/fields/Application_Status__c.field-meta.xml
<CustomField>
    <fullName>Application_Status__c</fullName>
    <description>The Status of the Job Application</description>
    <inlineHelpText>The Status of the Job Application</inlineHelpText>
    <label>Application Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Saved</fullName>
                <default>true</default>
                <label>Saved</label>
            </value>
            <value>
                <fullName>Not Interested</fullName>
            </value>
            <value>
                <fullName>Applying</fullName>
            </value>
            <value>
                <fullName>Applied</fullName>
            </value>
            <value>
                <fullName>Interviewing</fullName>
            </value>
            <value>
                <fullName>Negotiating</fullName>
            </value>
            <value>
                <fullName>Offer Declined</fullName>
            </value>
            <value>
                <fullName>Offer Accepted</fullName>
            </value>
            <value>
                <fullName>No Offer</fullName>
            </value>
            <value>
                <fullName>Auto Close - Stale</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Job_Application__c/fields/Follow_Up_Date__c.field-meta.xml
<CustomField>
    <fullName>Follow_Up_Date__c</fullName>
    <description>The date that the applicant should next follow-up on the job</description>
    <inlineHelpText>The date that the applicant should next follow-up on the job</inlineHelpText>
    <label>Follow-Up Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Job_Application__c/fields/Job_Posting_Id__c.field-meta.xml
<CustomField>
    <fullName>Job_Posting_Id__c</fullName>
    <description>The Id of the Job Posting from the external website</description>
    <externalId>true</externalId>
    <inlineHelpText>The Id of the job posting listed on the external website</inlineHelpText>
    <label>Job Posting Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/JobApplicationSelector.cls
public with sharing class JobApplicationSelector {

    public static List<Job_Application__c> getJobAppsWithExternalJobId(Set<String> externalJobIds) {

        if (externalJobIds.isEmpty()) {
            Utility.throwIllegalArgumentException('The externalJobIds argument was null.');
        }
        
        List<Job_Application__c> jobApps = new List<Job_Application__c>();
        if (!externalJobIds.isEmpty()) {
            jobApps = [
                SELECT Id, Job_Posting_Id__c
                FROM Job_Application__c
                WHERE Job_Posting_Id__c IN :externalJobIds
            ];
        }
        return jobApps;
    }

    public static List<Job_Application__c> getJobAppsWithOpenTasks(Set<Id> jobAppIdsToGet) {

        if (jobAppIdsToGet.isEmpty()) {
            Utility.throwIllegalArgumentException('The jobAppIdsToGet variable is null');
        }

        List<Job_Application__c> jobAppsWithOpenTasks = [
            SELECT Id,
                (SELECT Id, IsClosed FROM Tasks WHERE WhatId IN :jobAppIdsToGet AND IsClosed = FALSE)
            FROM Job_Application__c
            WHERE Id IN :jobAppIdsToGet
        ];
        return jobAppsWithOpenTasks;
    }

    public static String getStaleJobApplications(Date staleDate) {

        String queryString = 'SELECT Id, Application_Status__c, Follow_Up_Date__c, Owner.Email, Owner.isActive ' +
        'FROM Job_Application__c ' +
        'WHERE Follow_Up_Date__c <= :staleDate ' + 
        'AND Application_Status__c NOT IN (\'Offer Declined\', \'Offer Accepted\', \'Not Interested\', \'No Offer\', \'Auto Close - Stale\')';
        return queryString;
    }
}