force-app/main/default/objects/Callout_Configuration__mdt/Callout_Configuration__mdt.object-meta.xml
<CustomObject>
    <description>Stores the data points needed to do a callout. Created since I couldn&apos;t use Named Credentials for Jooble since the API key is expected in the URL.</description>
    <label>Callout Configuration</label>
    <pluralLabel>Callout Configurations</pluralLabel>
</CustomObject>

force-app/main/default/objects/Callout_Configuration__mdt/fields/API_Key__c.field-meta.xml
<CustomField>
    <fullName>API_Key__c</fullName>
    <description>API Key for the callout</description>
    <label>API Key</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Callout_Configuration__mdt/fields/Body__c.field-meta.xml
<CustomField>
    <fullName>Body__c</fullName>
    <description>Body for the callout. Parts of the body surrounded in *** are values that the Apex code will replace with the appropriate values at run time.</description>
    <label>Body</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Callout_Configuration__mdt/fields/Endpoint__c.field-meta.xml
<CustomField>
    <fullName>Endpoint__c</fullName>
    <description>The endpoint for the callout</description>
    <label>Endpoint</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Callout_Configuration__mdt/fields/Header_Key__c.field-meta.xml
<CustomField>
    <fullName>Header_Key__c</fullName>
    <description>The key for the Header used in the callout</description>
    <label>Header Key</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Callout_Configuration__mdt/fields/Header_Value__c.field-meta.xml
<CustomField>
    <fullName>Header_Value__c</fullName>
    <description>Value of the header for the callout</description>
    <label>Header Value</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Callout_Configuration__mdt/fields/Max_Pages__c.field-meta.xml
<CustomField>
    <fullName>Max_Pages__c</fullName>
    <description>When working with the Jooble API, I have noticed something weird. If you search different keywords, you&apos;ll get a data point back that says total jobs and this number varies based on the keywords. This suggests that this is the total jobs that match your keywords. Typically, for Salesforce Developer in Austin, TX, I am seeing 6000+ jobs returned. If you request 100 jobs per page, this suggests that there should be 60 pages of results. However, whenever I call the API requesting 100 records per page and request page 13 or higher, it returns no jobs. Same thing happens when my keywords are &quot;Customer Service&quot; or &quot;Java Developer&quot; - it basically doesn&apos;t let me request Page 13 or higher. As a result, this stores the max amount of pages we will attempt to get so that the LWC can have pagination based on the total records.</description>
    <label>Max Pages</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Callout_Configuration__mdt/fields/Method__c.field-meta.xml
<CustomField>
    <fullName>Method__c</fullName>
    <description>Method for the callout</description>
    <label>Method</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Callout_Configuration__mdt/fields/Record_Count_To_Get__c.field-meta.xml
<CustomField>
    <fullName>Record_Count_To_Get__c</fullName>
    <description>Number of records to get in the API call</description>
    <label>Record Count To Get</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Integration_Field_Mapping__mdt/Integration_Field_Mapping__mdt.object-meta.xml
<CustomObject>
    <description>For an integration, this Custom Metadata Type creates mappings between:
- The name of the key in the data received in the integration
- A Salesforce Object / field it should correspond to, if applicable (not required if we don&apos;t end up mapping a data point to this field
- A display name for this data point that can be used in the UI, such as an LWC</description>
    <label>Integration Field Mapping</label>
    <pluralLabel>Integration Field Mappings</pluralLabel>
</CustomObject>

force-app/main/default/objects/Integration_Field_Mapping__mdt/fields/Key__c.field-meta.xml
<CustomField>
    <fullName>Key__c</fullName>
    <description>The key to identify a given data point</description>
    <label>Key</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Job_Application__c/Job_Application__c.object-meta.xml
<CustomObject>
    <description>Tracks Job Applications throughout the whole lifecycle of the application.</description>
    <label>Job Application</label>
    <nameField>
        <displayFormat>JA-{00000}</displayFormat>
        <label>Job Application Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Job_Application__c/fields/Job_Posting_Id__c.field-meta.xml
<CustomField>
    <fullName>Job_Posting_Id__c</fullName>
    <description>The Id of the Job Posting from the external website</description>
    <externalId>true</externalId>
    <inlineHelpText>The Id of the job posting listed on the external website</inlineHelpText>
    <label>Job Posting Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Job_Application_Contact__c/Job_Application_Contact__c.object-meta.xml
<CustomObject>
    <description>Junction Object between Job Application and Contact so that there can be a many to many relationship between the two.</description>
    <label>Job Application Contact</label>
    <nameField>
        <displayFormat>JAC-{0000}</displayFormat>
        <label>Job Application Contact Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Application Contacts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Job_Application_Contact__c/fields/Job_Application__c.field-meta.xml
<CustomField>
    <fullName>Job_Application__c</fullName>
    <description>Primary Master-Detail relationship for the Junction Object.</description>
    <inlineHelpText>Job Application associated with the Job Application Contact</inlineHelpText>
    <label>Job Application</label>
    <referenceTo>Job_Application__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Job_Application_Contacts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/JobBoardCallout.cls
public with sharing class JobBoardCallout {

    // Didn't go cacheable = true because if a user refreshes the same search on the LWC, nothing happens and it is weird
    @AuraEnabled
    public static Map<String, Object> getJobs (String jobKeywords, String jobLocation, String pageNumber) {
        
        if (jobKeywords == null || jobLocation == null || pageNumber == null) {
            Utility.throwIllegalArgumentException('An argument was null.');
        }

        // Get details of the callout to be performed from Custom Metadata
        Callout_Configuration__mdt calloutDetails = Callout_Configuration__mdt.getInstance('Jooble_Post');
        
        // Call various methods that help process, check and prepare the data
        HttpResponse calloutResponse = performJoobleCallout(jobKeywords, jobLocation, pageNumber, calloutDetails);
        Map<String, Object> deserializedJson = deserializeJsonAndCheckForKeys(calloutResponse.getBody());
        List<Map<String, Object>> jobsDataByAttributes = extractListOfJobsFromJson(deserializedJson, 'jobs');
        Integer jobCountFromDeserializedJson = Integer.valueOf(deserializedJson.get('totalCount'));
        checkJobDataForMissingInfo(jobsDataByAttributes, jobCountFromDeserializedJson);
        List<Integration_Field_Mapping__mdt> jobDataKeys = 
            IntegrationFieldMappingSelector.getMappingsFromRelatedCalloutConfig(calloutDetails.Id);
        
        // Get mappings that will help map fields from the integration to SF Job Application records
        Integration_Field_Mapping__mdt idMapping = IntegrationFieldMappingHelper.getIdMapping(jobDataKeys);
        if (idMapping == null || jobDataKeys.isEmpty()) {
            Utility.throwAuraHandledException('The CMDT integration mappings are not setup correctly.');
        }

        // Call methods that help validate if the Job Applications already exist in SF and shouldn't be shown for selection
        Set<String> jobIds = extractJobIdsFromJobs(jobsDataByAttributes, idMapping);
        List<Job_Application__c> jobsAlreadySaved = JobApplicationSelector.getJobAppsWithExternalJobId(jobIds);
        if (jobIds.size() == jobsAlreadySaved.size()) {
            Utility.throwUiFriendlyException('You have already saved all of the jobs returned by the search!');
        }
        Set<String> alreadySavedJobIds = new Set<String>();
        if (!jobsAlreadySaved.isEmpty()) {
            alreadySavedJobIds = Utility.getSetOfStringsFromField(jobsAlreadySaved, 'Job_Posting_Id__c');
        }
        
        // Prepare the job data in a format that can be consumed by the client
        List<Map<String, String>> jobDataForClient = IntegrationFieldMappingHelper.prepareJobDataForUserSelection(
            jobDataKeys, idMapping.Key__c, jobsDataByAttributes, alreadySavedJobIds);

        /* When calling the Jooble API, it was saying it had a specified amount of Jobs, but when I was trying to navigate
        through pages to get them, it just cut off returning jobs at a certain point, way below the total jobs. So, this is just
        to set a max number of pages based on what I saw so this didn't happen in the UI. I have a video if you care for future
        cohorts - it was a time suck figuring out what was going on!*/
        Integer maxPagesToDisplay = calculateMaxPagesOfJobs(calloutDetails, jobCountFromDeserializedJson);
        Integer maxJobs = calculateMaxJobsToDisplay(calloutDetails, maxPagesToDisplay);

        // Bundle the job data with the job count and return that to the LWC
        Map<String, Object> jobDataAndVolumeForClient = new Map<String, Object>();
        jobDataAndVolumeForClient.put('jobs', jobDataForClient);
        jobDataAndVolumeForClient.put('jobCount', maxJobs);
        jobDataAndVolumeForClient.put('maxPages', maxPagesToDisplay);
        return jobDataAndVolumeForClient;
    }

    public static HttpResponse performJoobleCallout (
        String jobKeywords, String jobLocation, String pageNumber, Callout_Configuration__mdt calloutDetails) {
        
        if (jobKeywords == null || jobLocation == null || pageNumber == null || calloutDetails == null) {
            Utility.throwIllegalArgumentException('An argument was null.');
        }
        
        // Create the callout request from CMDT passed into the method
        Http callout = new Http();
        HttpRequest calloutRequest = new HttpRequest();
        String calloutString = calloutDetails.Body__c;
        calloutString = calloutString.replace('***jobKeywords***', jobKeywords);
        calloutString = calloutString.replace('***jobLocation***', jobLocation);
        calloutString = calloutString.replace('***recordCount***', calloutDetails.Record_Count_To_Get__c);
        calloutString = calloutString.replace('***pageNumber***', pageNumber);
        calloutRequest.setBody(calloutString);
        calloutRequest.setEndpoint(calloutDetails.Endpoint__c + calloutDetails.API_Key__c);
        calloutRequest.setMethod(calloutDetails.Method__c);
        calloutRequest.setHeader(calloutDetails.Header_Key__c, calloutDetails.Header_Value__c);
        
        // Send the callout and throw an exception back to the client if we have an issue.
        HttpResponse calloutResponse = callout.send(calloutRequest);
        if (!Utility.checkIfResponseCodeIsSuccess(calloutResponse.getStatusCode())){
            Utility.throwCalloutException(
                calloutResponse.getStatusCode(), 'An error occurred with a callout.');
        }
        // Return successful callout
        return calloutResponse;
    }

    public static Map<String, Object> deserializeJsonAndCheckForKeys (String calloutResponse) {
        // Deserialize the JSON and check the expected keys are present
        Map<String, Object> deserializedJson = Utility.deserializeJson(calloutResponse);
        if (!deserializedJson.containsKey('totalCount')) {
            Utility.throwAuraHandledException('The job data is missing the totalCount key.');
        }
        if (!deserializedJson.containsKey('jobs')) {
            Utility.throwAuraHandledException('The job data is missing the jobs key.');
        }
        return deserializedJson;
    }

    public static List<Map<String, Object>> extractListOfJobsFromJson(Map<String, Object> deserializedJson, String jobsKey) {
        if (deserializedJson.isEmpty() || jobsKey == null) {
            Utility.throwIllegalArgumentException('An argument was null.');
        }
        List<Object> jobsFromKey = (List<Object>)deserializedJson.get(jobsKey);
        List<Map<String, Object>> jobsDataByAttributes = new List<Map<String, Object>>();
        for (Object job : jobsFromKey) {
            Map<String, Object> jobByKey = (Map<String, Object>)job;
            jobsDataByAttributes.add(jobByKey);
        }
        return jobsDataByAttributes;
    }
    
    public static void checkJobDataForMissingInfo (List<Map<String, Object>> jobDataBeforeProcessing, Integer jobCount) {
        Map<String, Object> mapWithErrorInfo = new Map<String, Object>();
        if (jobDataBeforeProcessing.isEmpty() || jobCount == null || jobCount == 0) {
            Utility.throwUiFriendlyException('No jobs met your search criteria. Try again!');
        }
    }

    public static Set<String> extractJobIdsFromJobs(
        List<Map<String, Object>> jobsDataByAttributes, Integration_Field_Mapping__mdt idMapping) {
        Set<String> extractedJobIds = new Set<String>();
        for (Map<String, Object> job : jobsDataByAttributes) {
            if (String.valueOf(job.get(idMapping.Key__c)) != null) {
                extractedJobIds.add(String.valueOf(job.get(idMapping.Key__c)));
            }
        }
        return extractedJobIds;
    }

    public static Integer calculateMaxPagesOfJobs(Callout_Configuration__mdt config, Integer totalJobCount) {

        if (config == null || totalJobCount == null) {
            Utility.throwIllegalArgumentException('An argument was null.');
        }

        Integer maxPagesToAllowInClient = 0;
        Integer maxJobsToDisplay = Integer.valueOf(config.Record_Count_To_Get__c) * Integer.valueOf(config.Max_Pages__c);
        if (totalJobCount > maxJobsToDisplay) {
            maxPagesToAllowInClient = Integer.valueOf(config.Max_Pages__c);
        } else {
            Math.ceil(maxPagesToAllowInClient = (totalJobCount / Integer.valueOf(config.Record_Count_To_Get__c)));
        }
        return maxPagesToAllowInClient;
    }

    public static Integer calculateMaxJobsToDisplay(Callout_Configuration__mdt config, Integer maxPages) {

        if (config == null || maxPages == null) {
            Utility.throwIllegalArgumentException('An argument was null.');
        }

        Integer maxJobsToDisplay = Integer.valueOf(config.Record_Count_To_Get__c) * maxPages;
        return maxJobsToDisplay;
    }
    
    @AuraEnabled
    public static String processSelectedJobs(List<Map<String, Object>> selectedJobs) {

        // Get CMDT that will help with mapping values from selected Jobs to SF Job Applications
        Id joobleCalloutId = Callout_Configuration__mdt.getInstance('Jooble_Post').Id;
        List<Integration_Field_Mapping__mdt> jobMappings = IntegrationFieldMappingSelector.getMappingsFromRelatedCalloutConfig(joobleCalloutId);

        // Find the field mappings that reference the Account and Job_Posting_Id as they are potentially used for Account names. Throw an exception if either are null
        // Ideally, I wouldn't call this method twice and do it in one call, but this prevents a last minute bug I found that I didn't have time to fix in a better way
        Integration_Field_Mapping__mdt accountNameMapping = IntegrationFieldMappingHelper.getCalloutMappingForObjectAndField(jobMappings, 'Account', 'Name');
        Integration_Field_Mapping__mdt jobPostingIdMapping = IntegrationFieldMappingHelper.getCalloutMappingForObjectAndField(jobMappings, 'Job_Application__c', 'Job_Posting_Id__c');
        if (accountNameMapping == null || jobPostingIdMapping == null) {
            Utility.throwAuraHandledException('A mapping to help identify existing Account records and set new Account Names could not be found.');
        }

        // Build a Set of Company Names so we can see if Accounts already exist for them
        // If the Job doesn't have a Company Name, the Job Posting Id will be in the Set and used as the Account Name
        Set<String> companyNamesForSelectedJobs = 
            Utility.getSingleStringFromEachMapInList(accountNameMapping.Key__c, jobPostingIdMapping.Key__c, selectedJobs);

        // Get Accounts and the oldest Contact associated with them, since they will be the Job App Contact if one exists
        List<Account> existingAccountsForCompanies = AccountSelector.getAccountsAndOldestContact(companyNamesForSelectedJobs);

        // Loop the Account records and build Maps that will help with processing later in the method
        Map<String, Account> accountsByCompanyName = new Map<String, Account>();
        Map<Id, String> accountNameById = new Map<Id, String>();
        for (Account acc : existingAccountsForCompanies) {
            accountsByCompanyName.put(acc.Name, acc);
            accountNameById.put(acc.Id, acc.Name);
        }

        // Return a Map of Account sObjects by Company Name for the companies that need one and then insert the Accounts
        Map<String, Account> newAccountsByCompanyName = 
            AccountHelper.generateAccountsForNamesNotInSet(companyNamesForSelectedJobs, accountsByCompanyName);
        if (!newAccountsByCompanyName.values().isEmpty()) {
            List<Account> newAccounts = Utility.insertRecords(newAccountsByCompanyName.values());
            // Add the new Accounts to the existing Account maps that will help with processing
            for (Account newAccountForJob : newAccounts) {
                accountsByCompanyName.put(newAccountForJob.Name, newAccountForJob);
                accountNameById.put(newAccountForJob.Id, newAccountForJob.Name);
            }
        }

        // Loop the selected Jobs and insert the Job Application records
        List<Job_Application__c> selectedJobApplications = JobApplicationHelper.generateJobApplicationsFromSelectedJobs(
            selectedJobs, accountNameMapping.Key__c, accountsByCompanyName, jobMappings);
        selectedJobApplications = Utility.insertRecords(selectedJobApplications);

        // Create Job Application Contacts when the Account associated with the Job Application has an exisitng Contact
        List<Job_Application_Contact__c> newJobAppContacts = JobApplicationContactHelper.generateContactsForNewJobApplications(
            selectedJobApplications, accountNameById, accountsByCompanyName, 'Existing Contact');
        if (!newJobAppContacts.isEmpty()) {
            newJobAppContacts = Utility.insertRecords(newJobAppContacts);
        }
        String message = 'Success';
        return message;
    }
}