force-app/main/default/objects/Callout_Configuration__mdt/Callout_Configuration__mdt.object-meta.xml
<CustomObject>
    <description>Stores the data points needed to do a callout. Created since I couldn&apos;t use Named Credentials for Jooble since the API key is expected in the URL.</description>
    <label>Callout Configuration</label>
    <pluralLabel>Callout Configurations</pluralLabel>
</CustomObject>

force-app/main/default/objects/Callout_Configuration__mdt/fields/Record_Count_To_Get__c.field-meta.xml
<CustomField>
    <fullName>Record_Count_To_Get__c</fullName>
    <description>Number of records to get in the API call</description>
    <label>Record Count To Get</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/JoobleCalloutMockGenerator.cls
@isTest
public with sharing class JoobleCalloutMockGenerator implements HttpCalloutMock {

	public HTTPResponse respond(HTTPRequest req) {

        Callout_Configuration__mdt joobleCallout = Callout_Configuration__mdt.getInstance('Jooble_Post');
		String mockResponse = TestDataFactory.generateTestJoobleCalloutString(Integer.valueOf(joobleCallout.Record_Count_To_Get__c));

		HttpResponse res = new HttpResponse();
		res.setHeader('Content-Type', 'application/json');
        res.setBody(mockResponse);
		res.setStatusCode(200);
		return res;
	}
}