force-app/main/default/objects/Callout_Configuration__mdt/Callout_Configuration__mdt.object-meta.xml
<CustomObject>
    <description>Stores the data points needed to do a callout. Created since I couldn&apos;t use Named Credentials for Jooble since the API key is expected in the URL.</description>
    <label>Callout Configuration</label>
    <pluralLabel>Callout Configurations</pluralLabel>
</CustomObject>

force-app/main/default/objects/Integration_Field_Mapping__mdt/Integration_Field_Mapping__mdt.object-meta.xml
<CustomObject>
    <description>For an integration, this Custom Metadata Type creates mappings between:
- The name of the key in the data received in the integration
- A Salesforce Object / field it should correspond to, if applicable (not required if we don&apos;t end up mapping a data point to this field
- A display name for this data point that can be used in the UI, such as an LWC</description>
    <label>Integration Field Mapping</label>
    <pluralLabel>Integration Field Mappings</pluralLabel>
</CustomObject>

force-app/main/default/objects/Integration_Field_Mapping__mdt/fields/Callout_Configuration__c.field-meta.xml
<CustomField>
    <fullName>Callout_Configuration__c</fullName>
    <description>If applicable, the related Callout Configuration.</description>
    <label>Callout Configuration</label>
    <referenceTo>Callout_Configuration__mdt</referenceTo>
    <relationshipLabel>Integration Field Mappings</relationshipLabel>
    <relationshipName>Integration_Field_Mappings</relationshipName>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/Integration_Field_Mapping__mdt/fields/LWC_Column_Data_Type__c.field-meta.xml
<CustomField>
    <fullName>LWC_Column_Data_Type__c</fullName>
    <description>The data type for the LWC column that will show the data.</description>
    <label>LWC Column Data Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Integration_Field_Mapping__mdt/fields/LWC_Column_Sort_Order__c.field-meta.xml
<CustomField>
    <fullName>LWC_Column_Sort_Order__c</fullName>
    <description>The order in which each data point will appear in the LWC data table. Lowest number starts on the left of the table.</description>
    <label>LWC Column Sort Order</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/IntegrationFieldMappingSelectorTest.cls
@isTest
public with sharing class IntegrationFieldMappingSelectorTest {

    @isTest
    static void getMappingsFromRelatedCalloutConfig() {

        Id joobleCalloutConfigId = Callout_Configuration__mdt.getInstance('Jooble_Post').Id;

        Test.startTest();
        List<Integration_Field_Mapping__mdt> mappings = IntegrationFieldMappingSelector.getMappingsFromRelatedCalloutConfig(joobleCalloutConfigId);
        Test.stopTest();

        for (Integration_Field_Mapping__mdt mapping : mappings) {
            Assert.areEqual(joobleCalloutConfigId, mapping.Callout_Configuration__c, 'The callout configuration on the returned mappings is not as expected');
        }
    }

    @isTest
    static void getMappingsFromRelatedCalloutConfig_illegalArgument() {

        Id nullId = null;
        Boolean exceptionThrown = false;

        Test.startTest();
        try {
            List<Integration_Field_Mapping__mdt> mappings = IntegrationFieldMappingSelector.getMappingsFromRelatedCalloutConfig(nullId);
        } catch (IllegalArgumentException e) {
            exceptionThrown = true;
        }
        Test.stopTest();

        Assert.isTrue(exceptionThrown, 'An Illegal Argument Exception should have been thrown');
    }

    @isTest
    static void getLwcColumnsFromIntegrationFieldMappings() {

        Id joobleCalloutConfigId = Callout_Configuration__mdt.getInstance('Jooble_Post').Id;

        Test.startTest();
        List<Integration_Field_Mapping__mdt> mappings = IntegrationFieldMappingSelector.getLwcColumnsFromIntegrationFieldMappings(joobleCalloutConfigId);
        Test.stopTest();

        Integer lastSortOrderValueLooped = null;
        for (Integration_Field_Mapping__mdt mapping : mappings) {
            if (lastSortOrderValueLooped == null) {
                lastSortOrderValueLooped = (Integer)mapping.LWC_Column_Sort_Order__c;
            } else {
                Assert.isTrue(mapping.LWC_Column_Sort_Order__c > lastSortOrderValueLooped, 'The LWC Column Sort Order of ' + mapping.LWC_Column_Sort_Order__c + ' should be greater than the last value looped of ' + lastSortOrderValueLooped);
                lastSortOrderValueLooped += 1;
            }
            Assert.areEqual(joobleCalloutConfigId, mapping.Callout_Configuration__c, 'The callout configuration on the returned mappings is not as expected');
            Assert.isNotNull(mapping.LWC_Column_Sort_Order__c, 'The LWC Column Sort Order field should not be null');
            Assert.isNotNull(mapping.LWC_Column_Data_Type__c, 'The LWC Column Data Type field should not be null');
        }
    }

    @isTest
    static void getLwcColumnsFromIntegrationFieldMappings_illegalArgument() {

        Id nullId = null;
        Boolean exceptionThrown = false;

        Test.startTest();
        try {
            List<Integration_Field_Mapping__mdt> mappings = IntegrationFieldMappingSelector.getLwcColumnsFromIntegrationFieldMappings(nullId);
        } catch (IllegalArgumentException e) {
            exceptionThrown = true;
        }
        Test.stopTest();

        Assert.isTrue(exceptionThrown, 'An Illegal Argument Exception should have been thrown');
    }
}