force-app/main/default/objects/Callout_Configuration__mdt/Callout_Configuration__mdt.object-meta.xml
<CustomObject>
    <description>Stores the data points needed to do a callout. Created since I couldn&apos;t use Named Credentials for Jooble since the API key is expected in the URL.</description>
    <label>Callout Configuration</label>
    <pluralLabel>Callout Configurations</pluralLabel>
</CustomObject>

force-app/main/default/objects/Integration_Field_Mapping__mdt/Integration_Field_Mapping__mdt.object-meta.xml
<CustomObject>
    <description>For an integration, this Custom Metadata Type creates mappings between:
- The name of the key in the data received in the integration
- A Salesforce Object / field it should correspond to, if applicable (not required if we don&apos;t end up mapping a data point to this field
- A display name for this data point that can be used in the UI, such as an LWC</description>
    <label>Integration Field Mapping</label>
    <pluralLabel>Integration Field Mappings</pluralLabel>
</CustomObject>

force-app/main/default/objects/Integration_Field_Mapping__mdt/fields/Field_API_Name__c.field-meta.xml
<CustomField>
    <fullName>Field_API_Name__c</fullName>
    <description>The API Name that the data in the key from the integration should map to</description>
    <label>Field API Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Integration_Field_Mapping__mdt/fields/ID_Field__c.field-meta.xml
<CustomField>
    <fullName>ID_Field__c</fullName>
    <defaultValue>false</defaultValue>
    <description>The field that is the unique identifier for a record received from the integration</description>
    <label>ID Field</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Integration_Field_Mapping__mdt/fields/Key__c.field-meta.xml
<CustomField>
    <fullName>Key__c</fullName>
    <description>The key to identify a given data point</description>
    <label>Key</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Integration_Field_Mapping__mdt/fields/LWC_Column_Data_Type__c.field-meta.xml
<CustomField>
    <fullName>LWC_Column_Data_Type__c</fullName>
    <description>The data type for the LWC column that will show the data.</description>
    <label>LWC Column Data Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Integration_Field_Mapping__mdt/fields/LWC_Column_Name__c.field-meta.xml
<CustomField>
    <fullName>LWC_Column_Name__c</fullName>
    <description>The column name to show in an LWC data table</description>
    <label>LWC Column Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Integration_Field_Mapping__mdt/fields/LWC_Type_Attributes__c.field-meta.xml
<CustomField>
    <fullName>LWC_Type_Attributes__c</fullName>
    <description>Type attributes for the data type that is shown in an LWC data table. For example, if you are showing a button in a cell, you can specify the variant (e.g. brand, destructive) in this field.</description>
    <label>LWC Type Attributes</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Integration_Field_Mapping__mdt/fields/Salesforce_Object__c.field-meta.xml
<CustomField>
    <fullName>Salesforce_Object__c</fullName>
    <description>The API Name of the Object that holds the field that a data point maps to</description>
    <label>Salesforce Object</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/IntegrationFieldMappingHelper.cls
public with sharing class IntegrationFieldMappingHelper {

    public static Integration_Field_Mapping__mdt getIdMapping (List<Integration_Field_Mapping__mdt> mappings) {
        
        if (mappings.isEmpty()){
            Utility.throwIllegalArgumentException('mappings arugment was null.');
        }
        
        Integration_Field_Mapping__mdt idMapping = new Integration_Field_Mapping__mdt();
        for (Integration_Field_Mapping__mdt mapping : mappings) {
            if (mapping.Id_Field__c) {
                idMapping = mapping;
                break;
            }
        }
        return idMapping;
    }

    public static Integration_Field_Mapping__mdt getCalloutMappingForObjectAndField (
        List<Integration_Field_Mapping__mdt> mappings,
        String objectMappedTo,
        String fieldApiNameMappedTo) {
        
        if (mappings.isEmpty() || objectMappedTo == null || fieldApiNameMappedTo == null){
            Utility.throwIllegalArgumentException('An argument was null.');
        }
        
        Integration_Field_Mapping__mdt mappingToReturn = new Integration_Field_Mapping__mdt();
        for (Integration_Field_Mapping__mdt mapping : mappings) {
            if (mapping.Salesforce_Object__c == objectMappedTo && mapping.Field_API_Name__c == fieldApiNameMappedTo) {
                mappingToReturn = mapping;
                break;
            }
        }
        return mappingToReturn;
    }

    public static List<Map<String, String>> prepareJobDataForUserSelection (
        List<Integration_Field_Mapping__mdt> jobDataMappings, 
        String jobIdMappingName, 
        List<Map<String, Object>> jobData, 
        Set<String> alreadySavedJobIds) {

        if (jobDataMappings.isEmpty() || jobData.isEmpty() || jobIdMappingName == null) {
            Utility.throwIllegalArgumentException('An argument was null.');
        }

        List<Map<String, String>> jobDataToReturn = new List<Map<String, String>>();
        for (Map<String, Object> job : jobData) {
            String jobId = String.valueOf(job.get(jobIdMappingName));
            // If the Job hasn't been saved in SF, prepare the data to be returned to the UI a User can select from
            if (!alreadySavedJobIds.contains(jobId)) {
                Map<String, String> jobToReturn = new Map<String, String>();
                for (Integration_Field_Mapping__mdt mapping : jobDataMappings) {
                    jobToReturn.put(mapping.Key__c, String.valueOf(job.get(mapping.Key__c)));
                }
                jobDataToReturn.add(jobToReturn);
            }
        }
        return jobDataToReturn;
    }

    public static sObject mapValuesToSingleSObject (
        List<Integration_Field_Mapping__mdt> mappings, 
        String targetSObject, 
        sObject record,
        Map<String, Object> dataToMap) {

        if (mappings.isEmpty() || targetSObject == null || dataToMap.isEmpty()) {
            Utility.throwIllegalArgumentException('An argument was null.');
        }
        
        for (Integration_Field_Mapping__mdt mapping: mappings) {
            if (mapping.Salesforce_Object__c == targetSObject && mapping.Field_API_Name__c != null) {
                record.put(mapping.Field_API_Name__c, String.valueOf(dataToMap.get(mapping.Key__c)));
            }
        }
        return record;
    }

    @AuraEnabled(cacheable=true)
    public static List<Map<String, Object>> getLwcColumnsFromIntegrationFieldMappings (String calloutConfigDevName) {

        if (calloutConfigDevName == null) {
            Utility.throwIllegalArgumentException('An argument was null.');
        }

        if (Callout_Configuration__mdt.getInstance(calloutConfigDevName) == null) {
            Utility.throwHandledException('There is no callout configuration in the Custom Metadata with the requested name.');
        }

        Id calloutConfigId = Callout_Configuration__mdt.getInstance(calloutConfigDevName).Id;
        List<Integration_Field_Mapping__mdt> dataForLwcColumnAttributes = 
            IntegrationFieldMappingSelector.getLwcColumnsFromIntegrationFieldMappings(calloutConfigId);

        if (dataForLwcColumnAttributes.isEmpty()) {
            Utility.throwHandledException('There are no column configurations in the Custom Metadata for this callout.');
        }

        List<Map<String, Object>> lwcColumnAttributes = new List<Map<String, Object>>();
        for (Integration_Field_Mapping__mdt columnData : dataForLwcColumnAttributes) {
            Map<String, Object> lwcColumn = new Map<String, Object>();
            lwcColumn.put('label', String.valueOf(columnData.LWC_Column_Name__c));
            lwcColumn.put('fieldName', String.valueOf(columnData.Key__c));
            lwcColumn.put('type', String.valueOf(columnData.LWC_Column_Data_Type__c));
            lwcColumn.put('sortable', 'true');
            if (columnData.LWC_Type_Attributes__c != null) {
                // Deserialize the JSON from Custom Metadata to customize the job URL
                Map<String, Object> deserializedTypeAttributes = Utility.deserializeJson(columnData.LWC_Type_Attributes__c);
                lwcColumn.put('typeAttributes', deserializedTypeAttributes);
            }
            lwcColumnAttributes.add(lwcColumn);
        }
        return lwcColumnAttributes;
    }
}