force-app/main/default/objects/SObject_Salary_Conversion_Class__mdt/SObject_Salary_Conversion_Class__mdt.object-meta.xml
<CustomObject>
    <description>SObjectSalaryConvert is an intertface. This CMDT tracks the names of classes that implement this interface. The classes that implement this interface handle converting salaries stored as Strings into Decimal values. Each Class handles a known pattern that we receive salaries in string format.</description>
    <label>SObject String Salary Conversion Class</label>
    <pluralLabel>SObject String Salary Conversion Classes</pluralLabel>
</CustomObject>

force-app/main/default/objects/SObject_Salary_Conversion_Class__mdt/fields/isActive__c.field-meta.xml
<CustomField>
    <fullName>isActive__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Provides an on / off switch for certain classes getting picked up in the logic, meaning we can turn off a particular pattern from getting converted, if needed.</description>
    <label>isActive</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/SObjectSalaryConversionClassSelectorTest.cls
@isTest
public with sharing class SObjectSalaryConversionClassSelectorTest {

    @isTest
    static void getActiveSalaryConversions() {

        Test.startTest();
        List<SObject_Salary_Conversion_Class__mdt> salaryConversions = 
        SObjectSalaryConversionClassSelector.getActiveSalaryConversions();
        Test.stopTest();

        for (SObject_Salary_Conversion_Class__mdt conversion : salaryConversions) {
            Assert.isTrue(conversion.isActive__c, 'The query should have only got active conversions');
        }
    } 
}