force-app/main/default/objects/SObject_Salary_Conversion_Class__mdt/SObject_Salary_Conversion_Class__mdt.object-meta.xml
<CustomObject>
    <description>SObjectSalaryConvert is an intertface. This CMDT tracks the names of classes that implement this interface. The classes that implement this interface handle converting salaries stored as Strings into Decimal values. Each Class handles a known pattern that we receive salaries in string format.</description>
    <label>SObject String Salary Conversion Class</label>
    <pluralLabel>SObject String Salary Conversion Classes</pluralLabel>
</CustomObject>

force-app/main/default/objects/SObject_Salary_Conversion_Class__mdt/fields/isActive__c.field-meta.xml
<CustomField>
    <fullName>isActive__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Provides an on / off switch for certain classes getting picked up in the logic, meaning we can turn off a particular pattern from getting converted, if needed.</description>
    <label>isActive</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/SObjectSalaryConversionClassSelector.cls
public with sharing class SObjectSalaryConversionClassSelector {

    public static List<SObject_Salary_Conversion_Class__mdt> getActiveSalaryConversions() {

        List<SObject_Salary_Conversion_Class__mdt> activeSalaryConversions = [
            SELECT Id, DeveloperName, isActive__c
            FROM SObject_Salary_Conversion_Class__mdt
            WHERE isActive__c = TRUE
        ];
        return activeSalaryConversions;
    }
}