force-app/main/default/objects/Status_Task_Manager__mdt/Status_Task_Manager__mdt.object-meta.xml
<CustomObject>
    <description>Represents the order of statuses in a business process and is used to determine Tasks to create at different steps as well as validating steps in the process aren&apos;t skipped. If two Statuses are different paths at the same point in the process, they should have the same value in the Order field. For example, for Job Application, Declined, Accepted and No Offer all have the same value. Task creation is optional at each status.</description>
    <label>Status Task Manager</label>
    <pluralLabel>Status Task Manager</pluralLabel>
</CustomObject>

force-app/main/default/objects/Status_Task_Manager__mdt/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates if the status is currently active in the business process</description>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Status_Task_Manager__mdt/fields/Process__c.field-meta.xml
<CustomField>
    <fullName>Process__c</fullName>
    <description>The name of the process. This is used so that the code can find the right Status Task Generators depending on the scenario.</description>
    <label>Process</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Job Application</fullName>
                <default>true</default>
                <label>Job Application</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/StatusTaskManagerSelectorTest.cls
@isTest
public with sharing class StatusTaskManagerSelectorTest {

    @isTest
    static void getActiveStatusConfigsForProcess() {

        Test.startTest();
        List<Status_Task_Manager__mdt> statusTaskManagers = 
            StatusTaskManagerSelector.getActiveStatusConfigsForProcess('Job Application');
        Test.stopTest();

        for (Status_Task_Manager__mdt stm : statusTaskManagers) {
            Assert.isTrue(stm.Active__c, 'The query should have only got Active Status Task Managers');
            Assert.areEqual('Job Application', stm.Process__c, 'The process hould be "Job Application');
        }
    }

    @isTest
    static void getActiveStatusConfigsForProcess_nullValue() {

        Boolean exceptionThrown = false;

        Test.startTest();
        try {
            List<Status_Task_Manager__mdt> statusTaskManagers = StatusTaskManagerSelector.getActiveStatusConfigsForProcess(null);
        } catch (IllegalArgumentException e) {
            exceptionThrown = true;
        }
        Test.stopTest();

        Assert.isTrue(exceptionThrown, 'An Illegal Argument Exception should have been thrown');
    }
}