force-app/main/default/objects/Integration_Field_Mapping__mdt/Integration_Field_Mapping__mdt.object-meta.xml
<CustomObject>
    <description>For an integration, this Custom Metadata Type creates mappings between:
- The name of the key in the data received in the integration
- A Salesforce Object / field it should correspond to, if applicable (not required if we don&apos;t end up mapping a data point to this field
- A display name for this data point that can be used in the UI, such as an LWC</description>
    <label>Integration Field Mapping</label>
    <pluralLabel>Integration Field Mappings</pluralLabel>
</CustomObject>

force-app/main/default/objects/Integration_Field_Mapping__mdt/fields/Callout_Configuration__c.field-meta.xml
<CustomField>
    <fullName>Callout_Configuration__c</fullName>
    <description>If applicable, the related Callout Configuration.</description>
    <label>Callout Configuration</label>
    <referenceTo>Callout_Configuration__mdt</referenceTo>
    <relationshipLabel>Integration Field Mappings</relationshipLabel>
    <relationshipName>Integration_Field_Mappings</relationshipName>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/Integration_Field_Mapping__mdt/fields/Field_API_Name__c.field-meta.xml
<CustomField>
    <fullName>Field_API_Name__c</fullName>
    <description>The API Name that the data in the key from the integration should map to</description>
    <label>Field API Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Integration_Field_Mapping__mdt/fields/ID_Field__c.field-meta.xml
<CustomField>
    <fullName>ID_Field__c</fullName>
    <defaultValue>false</defaultValue>
    <description>The field that is the unique identifier for a record received from the integration</description>
    <label>ID Field</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Integration_Field_Mapping__mdt/fields/Key__c.field-meta.xml
<CustomField>
    <fullName>Key__c</fullName>
    <description>The key to identify a given data point</description>
    <label>Key</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Integration_Field_Mapping__mdt/fields/LWC_Column_Data_Type__c.field-meta.xml
<CustomField>
    <fullName>LWC_Column_Data_Type__c</fullName>
    <description>The data type for the LWC column that will show the data.</description>
    <label>LWC Column Data Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Integration_Field_Mapping__mdt/fields/LWC_Column_Name__c.field-meta.xml
<CustomField>
    <fullName>LWC_Column_Name__c</fullName>
    <description>The column name to show in an LWC data table</description>
    <label>LWC Column Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Integration_Field_Mapping__mdt/fields/LWC_Column_Sort_Order__c.field-meta.xml
<CustomField>
    <fullName>LWC_Column_Sort_Order__c</fullName>
    <description>The order in which each data point will appear in the LWC data table. Lowest number starts on the left of the table.</description>
    <label>LWC Column Sort Order</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Integration_Field_Mapping__mdt/fields/LWC_Type_Attributes__c.field-meta.xml
<CustomField>
    <fullName>LWC_Type_Attributes__c</fullName>
    <description>Type attributes for the data type that is shown in an LWC data table. For example, if you are showing a button in a cell, you can specify the variant (e.g. brand, destructive) in this field.</description>
    <label>LWC Type Attributes</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Integration_Field_Mapping__mdt/fields/Salesforce_Object__c.field-meta.xml
<CustomField>
    <fullName>Salesforce_Object__c</fullName>
    <description>The API Name of the Object that holds the field that a data point maps to</description>
    <label>Salesforce Object</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/IntegrationFieldMappingSelector.cls
public with sharing class IntegrationFieldMappingSelector {

    @AuraEnabled(cacheable=true)
    public static List<Integration_Field_Mapping__mdt> getMappingsFromRelatedCalloutConfig(Id calloutConfigId) {

        if (calloutConfigId == null) {
            Utility.throwIllegalArgumentException('The calloutConfigId arugment was null.');
        }
        
        List<Integration_Field_Mapping__mdt> jobDataKeys = [
            SELECT Id, DeveloperName, Salesforce_Object__c, Field_API_Name__c, Id_Field__c, Key__c, Callout_Configuration__c
            FROM Integration_Field_Mapping__mdt
            WHERE Callout_Configuration__c = :calloutConfigId
        ];
        return jobDataKeys;
    }

    public static List<Integration_Field_Mapping__mdt> getLwcColumnsFromIntegrationFieldMappings (Id calloutConfigId) {

        if (calloutConfigId == null) {
            Utility.throwIllegalArgumentException('The calloutConfigId arugment was null.');
        }

        List<Integration_Field_Mapping__mdt> lwcColumnData = [
            SELECT Id, DeveloperName, LWC_Column_Name__c, LWC_Column_Data_Type__c, LWC_Column_Sort_Order__c, LWC_Type_Attributes__c, Key__c, Callout_Configuration__c
            FROM Integration_Field_Mapping__mdt
            WHERE Callout_Configuration__c = :calloutConfigId
            AND LWC_Column_Data_Type__c != null
            AND LWC_Column_Sort_Order__c != null
            ORDER BY LWC_Column_Sort_Order__c ASC
        ];
        return lwcColumnData;
    } 
}